set_property SRC_FILE_INFO {cfile:{C:/Users/jungu/Desktop/AiSys/AiSys_cpu/cpu/Assign 7.srcs/constrs_1/new/cpu.xdc} rfile:{../../../Assign 7.srcs/constrs_1/new/cpu.xdc} id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D9 [get_ports reset_n]
